# Generated by Django 3.2.5 on 2021-08-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenciaVotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_user', models.CharField(max_length=14, verbose_name='CPF')),
                ('conferir_voto', models.IntegerField(verbose_name='Voto')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto_lula', models.IntegerField(verbose_name='Voto lula')),
                ('voto_bolsonaro', models.IntegerField(verbose_name='Voto bolsonaro')),
                ('voto_ciro_gomes', models.IntegerField(verbose_name='Voto ciro gomes')),
                ('voto_mandeta', models.IntegerField(verbose_name='Voto mandeta')),
                ('voto_joao_doria', models.IntegerField(verbose_name='Voto joao foria')),
                ('voto_branco', models.IntegerField(verbose_name='Voto branco')),
                ('voto_nao_sabe', models.IntegerField(verbose_name='Voto não sabe')),
            ],
        ),
    ]
